site_name: wiki.morifuku.net
site_description: morifuku wiki
site_author: Shigeru Morifuku
site_url: https://wiki.morifuku.net
repo_name: morifuku/wiki
repo_url: https://github.com/morifuku/wiki
copyright: Copyright &copy 2023 Shigeru Morifuku
extra:
  analytics:
    provider: google
    property: G-K3D27V0BJG
theme:
    name: material
    locale: ja
    favicon: assets/images/ladybug5G32.ico
    logo: assets/images/favicon48.png
    features:
    - navigation.sections
    - navigation.tabs
nav:
  - A. Linux編:
    - Linux編: linux/index.md
    - A-4. 共通:
      - 1. IPv6の無効化/再有効化の設定: linux/ipv6-setting.md
    - A-11. Boot:
      - 1. OpenShiftのためのMatchBox設定: boot/matchbox.md
    - A-12. DPDK:
      - 概要: dpdk/index.md
      - 1. RHEL8にDPDK22インストール : dpdk/rhel8-dpdk22-install.md
      - 2. CentOS7にDPDK22インストール : dpdk/centos7-dpdk22-install.md
  - B. Virtualization編:
    - Virtualization編: virtualization/index.md
  - E. Application編:
    - Application編: application/index.md
    - E-1. OpenAirInterface5G:
      - 1. Docker/Ubuntu22でOAI5Gを動かす : oai5g/oai5g-ubu22.md
    - E-11 SIPp:
      - 1. Ubuntu22にSIPp 3.7.1をデプロイする: sipp/sipp-install.md
      - 2. Windows10にSIPp 3.6.1をデプロイする: sipp/windows-sipp.md
    - E-12 iperf3:
      - 1. IPv6でiperf3を使ってみる: tool/iperf3.md
    - E-21 基本アプリ:
      - 1. postfix/devecot設定: basic/mail.md