site_name: www.morifuku.net
site_description: morifuku.new
site_author: Shigeru Morifuku
site_url: https://www.morifuku.net
repo_name: morifuku/www
repo_url: https://github.com/morifuku/www
copyright: Copyright &copy 2023 Shigeru Morifuku
extra:
  analytics:
    provider: google
    property: G-K3D27V0BJG
theme:
    name: material
    locale: ja
    features:
    - navigation.sections
    - navigation.tabs
nav:
    - Home:
        - Home/index.md
